### ISSUE TITLE
No files matching the pattern "/__uno.css" were found.

### ISSUE THREAD

**Issue by fit2cloud-mahaoyu** [ModyQyW/vite-plugin-stylelint#12]
Prompt "No files matching the pattern "/__uno.css" were found."
And I can't close or ignore it.
<img width="660" alt="image" src="https://user-images.githubusercontent.com/81545871/176334754-c300fe3d-8579-4a88-b142-4a0f450c7108.png">

**Comment by ModyQyW** [comment]
Can you please provide a minimal reproduction?

**Comment by hackyoMa** [comment]
---init---
`npm create vite@latest my-vue-app -- --template vue-ts`
`cd my-vue-app && npm install`
`npm install --save-dev stylelint stylelint-config-standard vite-plugin-stylelint unocss`

---vite.config.ts---
`import { defineConfig } from 'vite'`
`import vue from '@vitejs/plugin-vue'`
`import Unocss from 'unocss/vite'`
`import StylelintPlugin from 'vite-plugin-stylelint'`
`export default defineConfig({`
`  plugins: [`
`    vue(),`
`    StylelintPlugin(),`
`    Unocss()`
`  ]`
`})`

---.stylelintrc.json---
`{`
`  "extends": "stylelint-config-standard",`
`  "ignoreFiles": ["**/*.vue"]`
`}`

---main.ts---
`import 'uno.css'`

**Comment by ModyQyW** [comment]
I don't know how to lint virtual files like `uno.css` or `__uno.css` because they actully not exist. One solution is to set `exclude`.

```ts
// vite.config.ts
import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import Unocss from "unocss/vite";
import StylelintPlugin from "vite-plugin-stylelint";

export default defineConfig({
  plugins: [
    vue(),
    StylelintPlugin({
      exclude: [/node_modules/, /uno\.css/],
    }),
    Unocss(),
  ],
});

```

PR welcome if you have better solution.

EDIT: IMO virtual files should be linted.

**Comment by ModyQyW** [comment]
I think I need to pin this. I actually know little about virtual modules. 😅

**Comment by hackyoMa** [comment]
No, what I need is to exclude.
I tried "exclude: ['uno.css']" and it didn't work
Now it works, thank you!

**Comment by ModyQyW** [comment]
v2.3.0 released. The plugin ignores virtual modules by default now. Open a new issue if someone is still facing this problem.
