### ISSUE TITLE
Missing typescript definition for `fix` option

### ISSUE THREAD

**Issue by mrleblanc101** [ModyQyW/vite-plugin-stylelint#13]
This option is not documented, but show in the first exemple.
![Capture d’écran, le 2022-07-06 à 16 53 29](https://user-images.githubusercontent.com/17392251/177641275-c74dc0b4-355f-4623-8a01-8381d8a556a6.png)

This option is not included in the type definition export.
<img width="864" alt="Capture d’écran, le 2022-07-06 à 16 51 07" src="https://user-images.githubusercontent.com/17392251/177641371-231be7a9-cc96-4bbc-8705-3880e32bd070.png">

So if I try to use it, my app wont build and throw this error:
> Argument of type '{ fix: boolean; }' is not assignable to parameter of type 'Options'.   Object literal may only specify known properties, and 'fix' does not exist in type 'Options'.

**Comment by mrleblanc101** [comment]
My bad, I did not have`stylelint` installed as a dependancy yet.
Only `vite-plugin-stylelint`, so the extend did not work.
But the error message was confusing.

**Comment by ModyQyW** [comment]
Types are better in v3.0.0. Please have a try.

**Comment by mrleblanc101** [comment]
I use 3.4.0, it's the extend that confused me.
VS Code also doesn't like it, but I have no build error, so it must work.
<img width="1824" alt="Capture d’écran, le 2022-07-13 à 14 02 08" src="https://user-images.githubusercontent.com/17392251/178800529-11c3d4c4-16b1-4bf2-a00b-e0c40b12ef8d.png">
