### ISSUE TITLE
Vite 3.0.0 support

### ISSUE THREAD

**Issue by matrunchyk** [ModyQyW/vite-plugin-stylelint#15]
Hello, thank you for your package! Any plans to bump to Vite@3.0.0? :)

**Comment by ModyQyW** [comment]
vite@3 should be supported from vite-plugin-stylelint@2.3.0. Anything wrong?

**Comment by ModyQyW** [comment]
Hi. Anything wrong with vite@3? @matrunchyk

**Comment by matrunchyk** [comment]
Hi @ModyQyW  it's all good, I probably tried before it was released. Thank you for your plugin!
