### ISSUE TITLE
Allow custom stylelint path

### ISSUE THREAD

**Issue by otakustay** [ModyQyW/vite-plugin-stylelint#2]
This plugins seems to have an implicit peer dependency on `stylelint` since it marks `stylelint` as external.

This solution causes an issue when we have a custom style lint installed in a nested toolkit, add a `stylelintPath` option can help to locate the correct `stylelint` implementation. [stylelint-webpack-plugin](https://webpack.js.org/plugins/stylelint-webpack-plugin/#stylelintpath) has this feature built-in.

Also, I recommend to use dynamic `import(options.stylelintPath || 'stylelint')` because it is possible that user project have no style files, in this situation we can optionally import `stylelint` to speed up.

**Comment by ModyQyW** [comment]
Sorry for the late response. @otakustay 

> This plugins seems to have an implicit peer dependency on stylelint since it marks stylelint as external.

Yes. I clarify it in README.md.

```md
vite-plugin-stylelint does not install and config Stylelint for you. You should handle these yourself.
```

> This solution causes an issue when we have a custom style lint installed in a nested toolkit, add a stylelintPath option can help to locate the correct stylelint implementation. [stylelint-webpack-plugin](https://webpack.js.org/plugins/stylelint-webpack-plugin/#stylelintpath) has this feature built-in.
> 
> Also, I recommend to use dynamic import(options.stylelintPath || 'stylelint') because it is possible that user project have no style files, in this situation we can optionally import stylelint to speed up.

Give me some time. May be longer than expected because I have been busy with company projects development. PR is welcome.

**Comment by ModyQyW** [comment]
@otakustay `stylelintPath` option and `stylelint` dynamic import have launched on `1.3.0-beta.0`. I also update README to make stylelint installation clearer. Take a try and give me some feedback. :D

**Comment by ModyQyW** [comment]
`eslintPath` option and `eslint` dynamic import have launched on `@modyqyw/vite-plugin-eslint@1.1.0-beta.0`. :D

**Comment by ModyQyW** [comment]
Closing it cause v2.0.0 is published. Feel free to open new issues. :D
