### ISSUE TITLE
Wrong `StylelintPluginOptions` type

### ISSUE THREAD

**Issue by szulcus** [ModyQyW/vite-plugin-stylelint#20]
### Describe the bug

```
Argument of type '{ fix: boolean; include: string[]; }' is not assignable to parameter of type 'StylelintPluginOptions'.
  Object literal may only specify known properties, and 'fix' does not exist in type 'StylelintPluginOptions'.ts(2345)
```

### Reproduction
In `nuxt.config.ts` file (Nuxt 3):
```ts
export default defineNuxtConfig({
	// ...
	vite: {
		plugins: [
			stylelint({
				fix: true,
			}),
		],
	}
});
```
![image](https://user-images.githubusercontent.com/48328739/198894814-55a81777-7b44-4078-af12-0df94ea67e7d.png)

### System Info
系统信息

```Shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
    Memory: 6.33 GB / 15.88 GB
  Binaries:
    Node: 16.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.0.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (107.0.1418.24)
    Internet Explorer: 11.0.22000.120
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ModyQyW/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ModyQyW** [comment]
I can't reproduce in my side. Have you installed deps correctly according to the README? You should install `vite-plugin-stylelint` and `stylelint` yourself.

<img width="866" alt="image" src="https://user-images.githubusercontent.com/31850793/198909286-9e6d4eaf-a6c8-4dd8-b634-1f3b207ea56c.png">

**Comment by szulcus** [comment]
@ModyQyW I had all the packages I needed installed. I think I had a problem with the editor. After opening the project today, everything works fine. Sorry for the confusion and thank you for the quick reply!

**Comment by ModyQyW** [comment]
Glad to hear you solved the problem ❤
