### ISSUE TITLE
Error breaks build

### ISSUE THREAD

**Issue by reintroducing** [ModyQyW/vite-plugin-stylelint#4]
When there is a Stylelint issue that is an error, it completely breaks the build:
![Screen Shot 2022-03-30 at 12 37 54 PM](https://user-images.githubusercontent.com/259901/160916924-63d83dd5-9aba-4f28-9254-1f20fc280342.png)
I can set `emitError: false` in the config but that just completely swallows the error. How can I get the error to show up in terminal still but not break the build? Sometimes I comment stuff out quickly or am just prototyping until I get to my final code and I don't want to have the errors break the build but I do want to still see them. Hopefully there is a way to make that happen with this plugin. Thanks.

**Comment by ModyQyW** [comment]
What about a new option `emitErrorAsWarning`? Is it enough for you? @reintroducing

**Comment by reintroducing** [comment]
Yes that would work, the key is just to not fail the build but rather show the error/warning in the terminal and continue. This is how the webpack stylelint plug-in works and even the vite eslint plug-in as well.

**Comment by ModyQyW** [comment]
Launched on v2.1.0. Feel free to open a new issue when you find a problem. :D

**Comment by reintroducing** [comment]
@ModyQyW Worked perfectly, really appreciate the quick turnaround on this. Thank you.
