### ISSUE TITLE
Update prettier to v3

### ISSUE THREAD

**Issue by websitevirtuoso** [ModyQyW/vite-plugin-stylelint#47]
### Clear and concise description of the problem

Update prettier to v3

### Suggested solution

Update prettier to v3

### Validations

- [X] Follow our [Code of Conduct](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ModyQyW** [comment]
Sorry but I don't get your point. Are you facing actual problems?
