### ISSUE TITLE
Failed to configure automatic recovery parameters

### ISSUE THREAD

**Issue by hzs0623** [ModyQyW/vite-plugin-stylelint#5]
Option configuration does not provide fix detection interface.
<img width="574" alt="image" src="https://user-images.githubusercontent.com/37969876/167160472-7a72506d-3aff-42af-bdb4-6b6b41d0d3e7.png">

missing parameter
<img width="519" alt="image" src="https://user-images.githubusercontent.com/37969876/167160531-eec86b7e-9355-44d3-b3da-ef9039053854.png">

**Comment by ModyQyW** [comment]
`Stylelint.LinterOptions` already includes `fix`. Can you please share a minimal reproduction for this problem?

**Comment by ModyQyW** [comment]
@hzs0623 👋🏻 Hi. I think this is a `tsconfig.json` problem. Can you please try update your `tsconfig.json`?

```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true
  }
}
```

It will be easier to debug if you can kindly share a minimal reproduction. Thanks.

**Comment by ModyQyW** [comment]
Please try 2.2.2. Reopen this issue if the problem still happens. Thanks.
