### ISSUE TITLE
Passing `context` to `lintFiles` when enable `chokidar` breaks the build

### ISSUE THREAD

**Issue by ModyQyW** [ModyQyW/vite-plugin-stylelint#51]
I apologize that I may not have expressed my opinion correctly and completely before. And sorry I am late in response.

Normally, enabling `lintInWorker` would only show errors and warnings in the console, but otherwise in the console and the browser.

Now, with `chokidar` enabled and `lintInWorker` disabled, I can't pass the context to the function (see https://github.com/ModyQyW/vite-plugin-stylelint/blob/v5.1.1/src/index.ts#L78-L98 comments) because it causes an error and just quits the Vite process. This leads to the problem mentioned in https://github.com/nuxt-modules/stylelint/issues/89, where the plugin only displays error and warning messages in the console, not in the browser.

I don't think adding an option called `failOnError` solves this problem. To fix this, we need to pass the context and avoid the error.

I think we only need to quit the process if the `lintOnStart` option is enabled and an error is checked, which would request the user to deal with the error that exists first to avoid caching issues ⬇️, which is exactly what this plugin currently behaves like.

<img width="854" alt="image" src="https://github.com/ModyQyW/vite-plugin-stylelint/assets/31850793/3a15b0c4-1014-4222-9eb0-89532478a149">

_Originally posted by @ModyQyW in https://github.com/ModyQyW/vite-plugin-stylelint/issues/50#issuecomment-1691082257_

**Comment by HawtinZeng** [comment]
Hi, how to show the debug content in the source code?
![image](https://github.com/ModyQyW/vite-plugin-stylelint/assets/73981739/91c099cd-5ba2-4da5-88b0-4939124d193e)

**Comment by ModyQyW** [comment]
I can confirm that it is caused by chokidar watch callback.

**Comment by ModyQyW** [comment]
I'm hoping that vite-plugin-stylelint 6.0.0-beta.0 will address the root cause of this issue and would like to gather feedback on it before the official release.

On @nuxtjs/stylelint-module 5.2.0, you can disable `lintDirtyOnly` to check all style files, including deep-imported files of course, but there is some performance loss.
