### ISSUE TITLE
Vite 5 semver in `peerDependencies`

### ISSUE THREAD

**Issue by khalwat** [ModyQyW/vite-plugin-stylelint#55]
### 描述问题

Now that Vite `^5.0.0` is released, probably the [peerDependencies](https://github.com/ModyQyW/vite-plugin-stylelint/blob/main/package.json#L92) should be updated:

from:

```json
    "vite": "^2.0.0 || ^3.0.0 || ^4.0.0 || 5.0.0-0"
```

to:

```json
    "vite": "^2.0.0 || ^3.0.0 || ^4.0.0 || ^5.0.0"
```

### 复现

n/a

### 系统信息

```Shell
n/a
```

### 使用的包管理器

npm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
Launched in v5.2.1. Thank you.
