### ISSUE TITLE
`output` is deprecated. Use `report` or `code` instead.

### ISSUE THREAD

**Issue by lmcsu** [ModyQyW/vite-plugin-stylelint#56]
### Describe the bug

The new version of stylelint shows that.
I think it's because of this line 
```
const result = { ...linterResult };
```

### Reproduction

Try to use it with stylelint@16

### System Info

```Shell
oh come on
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ModyQyW** [comment]
Yes, it is caused by stylelint. But we don't use `output` at all. Any thoughts?

**Comment by lmcsu** [comment]
As I told, I think it's because of this line
```
const result = { ...linterResult };
```

When you spread it like this, it reads all the properties from the `linterResult` object.
Including "output", that seems to be some kind of getter, not a static property.

**Comment by lmcsu** [comment]
Yep, that's right

stylelint/lib/prepareReturnValue.mjs:
```js
const returnValue = {
    cwd,
    errored,
    results: [],
    report: '',

    // TODO: Deprecated. Remove in the next major version.
    get output() {
        if (!this._outputWarned) {
            console.warn('`output` is deprecated. Use `report` or `code` instead.');
            this._outputWarned = true;
        }

        return this._output ?? '';
    },

    reportedDisables: [],
    ruleMetadata: getRuleMetadata(stylelintResults),
};
```

**Comment by ModyQyW** [comment]
> As I told, I think it's because of this line
> 
> ```
> const result = { ...linterResult };
> ```
> 
> When you spread it like this, it reads all the properties from the `linterResult` object. Including "output", that seems to be some kind of getter, not a static property.

Ah yes. Sorry, I have some misunderstandings. Now I am thinking of adding `delete linterResult.output` before `const result = { ...linterResult };`, which works fine in my local machine. I am not sure if it may break something or not. What do you think?

**Comment by lmcsu** [comment]
> What do you think?

seems dangerous...

**Comment by ModyQyW** [comment]
Yeah, I'm hesitant too...

**Comment by ModyQyW** [comment]
Just release v5.3.1. Hope this helps. @lmcsu

**Comment by lmcsu** [comment]
Yeah, it looks fine now, thank you :)

**Comment by ModyQyW** [comment]
I am using linterResult directly. I don't like it but I think it is a solution better than deleting some properties. Feel free to open a new issue if you have a new problem. 👍

**Comment by hatedMe** [comment]
@ModyQyW  release v5.3.1 Unable to fix on window.  It cannot be fixed on window, but it can be run and automatically fixed on mac system. This seems to be related to the operating system?
```js
stylelintPlugin({
      lintInWorker: true,
      cache: true,
      cacheLocation: path.resolve(__dirname, "./node_modules/.cache/stylelint"),
      chokidar: true,
      fix: true
  })
```

### Version:
```
    OS: Windows 10 10.0.19045
    CPU: (32) x64 13th Gen Intel(R) Core(TM) i9-13900K
    Memory: 8.38 GB / 31.75 GB
  Browsers:
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    "prettier": "^3.2.5",
    "stylelint": "^16.5.0",
    "vite": "^5.2.11",
    "vite-plugin-stylelint": "^5.3.1", 
```

**Comment by hatedMe** [comment]
@ModyQyW hi, After my debug positioning, I found that there is a problem with the function `isVirtualModule` in line 89 of the `/src/utils.ts` code. For example, in the window, the files id is `D:\work\qw-h5\src\views\ home\index.scss` This should not be a virtual module, it is real.
```js
// /src/utils.ts
export const isVirtualModule = (id: string) =>
  id.startsWith('virtual:') || id[0] === '\0' || !id.includes('/');
```

**Comment by ModyQyW** [comment]
Do please open a new issue. @hatedMe
