### ISSUE TITLE
When running auditjs, a warning appears for this plugin.

### ISSUE THREAD

**Issue by zzpmaster** [ModyQyW/vite-plugin-stylelint#59]
### Describe the bug

When using auditjs, the following error occurs
```
  (node:5324) [DEP0170] DeprecationWarning: The URL git+https://github.com:ModyQyW/vite-plugin-stylelint.git is invalid. Future versions of Node.js will throw an error.
(Use `node --trace-deprecation ...` to show where the warning was created)
```
I suspect the repository address in package.json is incorrect; it should be `/` instead of `:` .

### Reproduction

  After installing this plugin in the project, running `pnpm dlx auditjs ossi --dev --xml` will reproduce the error.

### System Info

```Shell
System:
    OS: macOS 14.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 153.29 MB / 16.00 GB
    Shell: 5.9
  Binaries:
    Node: 20.10.0 
    npm: 10.2.3 
    pnpm: 8.11.0 
  Browsers:
    Chrome: 129.0.6668.101
    Edge: 130.0.2849.46
    Safari: 17.6
    Safari Technology Preview: 17.4
```

### Used Package Manager

pnpm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/ModyQyW/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ModyQyW** [comment]
Thank you! The fix should be included in v6.0.0-beta.1
